/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package example;

import java.lang.FiberScope;
import java.util.concurrent.CountDownLatch;

public class App {

    private static final int LOOPS = 1_000_000;

    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws InterruptedException {

        CountDownLatch latch = new CountDownLatch(LOOPS);

        for (int i = 0; i < LOOPS; i++) {
            FiberScope.background().schedule(() -> {
//                System.out.println("Running in: " + Thread.currentThread().getName());

                try {
                    Thread.sleep(100L);
                } catch (InterruptedException e) {
                    throw new UnsupportedOperationException(); // TODO: Replace
                }
//                System.out.println("done");
                latch.countDown();
            });
        }

        System.out.println(new App().getGreeting());

        latch.await();
    }
}
